### ISSUE TITLE
Financial Goals (Budget System)

### ISSUE THREAD

**Issue by emilyjiji** [spwalgren/Student-Budget-Tracker#2]
As a site user, I would like to create financial goals so that I can be focused on my savings and spending to achieve this goal.

**Comment by Brian-Magnuson** [comment]
# Budget System

- Users can enter a number representing their "spending limit" for a particular category.
- Users can set a time frame for their goal.
- Users can decide whether their goal repeats, how often it repeats, and when it repeats.
- The budget system is set up like a digital calendar, but uses spending goals instead of repeating events.

**Comment by Brian-Magnuson** [comment]
Current state of budget system. CRUD functionality to be added. Displays period information, including information about the current period based on the current time.

![image](https://user-images.githubusercontent.com/92892499/227569961-8d451083-9083-478b-8014-e43f6e21c78a.png)

**Comment by emilyjiji** [comment]
Adding a new budget, currently minor formatting issues when selecting date:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/92887308/227715950-1014e3c9-f361-4d7e-9f13-9ab49f599d83.png">

**Comment by Brian-Magnuson** [comment]
CRUD functionality of budget system implemented and linked with backend. Ready to pull request soon.

![msedge_wLGjSvLpvw](https://user-images.githubusercontent.com/92892499/228566804-b38d2899-ebf8-417c-b044-2b21458b89ba.gif)
